# We use kramdown for TOC generation.
# See http://www.seanbuscay.com/blog/jekyll-toc-markdown for details:
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Monix
tagline:          'Asynchronous Programming for Scala & Scala.js'
description:      'Scala/Scala.js library for composing asynchronous, event-based programs.'
url:              https://monix.io
baseurl:          /

exclude:
  ["README.md", "deploy.sh", "CNAME", "vendor", "src", "project/", "build.sbt", "docs-raw",   "_tut", "target", "scripts"]

author:
  name:           'Alexandru Nedelcu'
  email:          'noreply@alexn.org'
  url:            'https://alexn.org'

permalink:     "/blog/:categories/:year/:month/:day/:title.html"
paginate_path: "/blog/page:num/"
paginate:      5

# Custom vars
version1x:     "1.2"
version2x:     "2.3.3"
version3x:     "3.0.0-RC1"

scalajs_full_version: 0.6.21
scalajs_pack_version: sjs0.6

# Last API path with which _tut gets generated
api1x:            /api/1.2/
api2x:            /api/2.3/
api3x:            /api/3.0/
apiJava:          https://docs.oracle.com/javase/8/docs/api/

docs2x:           /docs/2x/
docs3x:           /docs/3x/

github:
  repo:           https://github.com/monix/monix
  docs:           https://github.com/monix/monix.io
  chat:           https://gitter.im/monix/monix

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-scalafiddle

scalafiddle:
  dependency: io.monix %%% monix % 2.3.3
