name: build
on:
  - push:
      branches-ignore:
        - 'master'
  - pull_request

# name: build
# on:
#   push:
#     # Action run will only be triggered on updates to master branch
#     branches:
#       - master

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@master

      - name: Set up Ruby 2.6 (for microsite)
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Cache Ruby Bundler
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Cache SBT Coursier
        uses: actions/cache@v1.1.2
        with:
          path: ~/.cache/coursier
          key: ${{ runner.os }}-sbt-coursier-${{ hashFiles('**/build.sbt') }}        
          
      - name: Install dependencies
        run: |
          gem update --system
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          ./scripts/sbt clean compile

      - name: Build
        run: |
          ./scripts/build
        env:
          VIMEO_API_TOKEN: ${{ secrets.VIMEO_API_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
